url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Freelance Web Designer San Francisco" # the name of your site, e.g. ACME Corp.
sitebar: Hey There! My name is Asa. I am a freelance web designer from the San Francisco Bay area. I work with Start-Ups, Freelancers, Developers and Designers. All around San Fracisco.